// cli-ai-text-editor/src/app/app.component.ts
import { Component, OnInit } from "@angular/core";
import { RouterOutlet } from "@angular/router";
import { invoke } from "@tauri-apps/api/core";
import { CliService } from "./services/cli.service";
import { NgIf } from "@angular/common";

@Component({
  selector: "app-root",
  imports: [RouterOutlet, NgIf],
  templateUrl: "./app.component.html",
  styleUrl: "./app.component.css",
})
export class AppComponent implements OnInit {
  greetingMessage = "";
  cliInfo = "";
  cliError = "";
  fileContent = "";

  constructor(private cliService: CliService) {}

  async ngOnInit() {
    console.log('AppComponent initializing...');
    const initialized = await this.cliService.initialize();
    console.log('CLI Service initialized:', initialized);
    if (initialized) {
      this.displayCliInfo();
      await this.loadFileContent();
      this.applyTheme();
    } else {
      this.cliError = "Failed to initialize CLI service. CLI arguments may not be available.";
    }
  }

  async loadFileContent() {
    console.log('Loading file content...');
    try {
      const content = await this.cliService.getFileContent();
      console.log('File content loaded:', content);
      if (content !== null) {
        this.fileContent = content;
      }
    } catch (error) {
      console.error('Error loading file content:', error);
      this.cliError = `Failed to read file content: ${error}`;
    }
  }

  displayCliInfo() {
    console.log('Displaying CLI info...');
    const matches = this.cliService.getMatches();
    console.log('Matches:', matches);
    if (matches) {
      const fileArg = this.cliService.getFileArgument();
      const outputArg = this.cliService.getOutputArgument();
      const isVerbose = this.cliService.isVerbose();
      const theme = this.cliService.getTheme();
      const subcommand = this.cliService.getSubcommand();
      const subcommandMatches = this.cliService.getSubcommandMatches();
      
      this.cliInfo = `File: ${fileArg || 'Not specified'}\n` +
                     `Output: ${outputArg || 'Not specified'}\n` +
                     `Verbose: ${isVerbose ? 'Yes' : 'No'}\n` +
                     `Theme: ${theme || 'Not specified'}\n` +
                     (subcommand ? `Subcommand: ${subcommand}\n` : '') +
                     (subcommandMatches ? `Subcommand Args: ${JSON.stringify(subcommandMatches, null, 2)}\n` : '') +
                     `All Args: ${JSON.stringify(this.cliService.getAllArguments(), null, 2)}`;
    } else {
      this.cliInfo = "No CLI arguments provided.";
    }
    console.log('CLI Info:', this.cliInfo);
  }

  applyTheme() {
    const theme = this.cliService.getTheme();
    if (theme) {
      if (theme === 'dark') {
        document.body.classList.add('dark-theme');
      } else if (theme === 'light') {
        document.body.classList.remove('dark-theme');
      }
    }
  }

  greet(event: SubmitEvent, name: string): void {
    event.preventDefault();

    // Learn more about Tauri commands at https://tauri.app/develop/calling-rust/
    invoke<string>("greet", { name }).then((text) => {
      this.greetingMessage = text;
    });
  }
}
<main class="container">
  <h1>Welcome to Tauri + Angular!</h1>

  <div class="row">
    <a href="https://tauri.app" target="_blank">
      <img src="/assets/tauri.svg" class="logo tauri" alt="Tauri logo" />
    </a>
    <a href="https://angular.io" target="_blank">
      <img src="/assets/angular.svg" class="logo angular" alt="Angular logo" />
    </a>
  </div>
  <p>Click on the logos to learn more about the frameworks</p>

  <div class="cli-info" *ngIf="!cliError">
    <h2>CLI Information</h2>
    <pre>{{ cliInfo }}</pre>
  </div>

  <div class="file-content" *ngIf="fileContent">
    <h2>File Content</h2>
    <pre>{{ fileContent }}</pre>
  </div>

  <div class="cli-error" *ngIf="cliError">
    <h2>CLI Error</h2>
    <p>{{ cliError }}</p>
  </div>

  <form class="row" (submit)="greet($event, greetInput.value)">
    <input #greetInput id="greet-input" placeholder="Enter a name..." />
    <button type="submit">Greet</button>
  </form>
  <p>{{ greetingMessage }}</p>

  <router-outlet />
</main>

// video-editor-rs/src/App.tsx
import { useState } from "react";
import reactLogo from "./assets/react.svg";
import { invoke } from "@tauri-apps/api/core";
import "./App.css";

function App() {
  const [greetMsg, setGreetMsg] = useState("");
  const [name, setName] = useState("");

  async function greet() {
    // Learn more about Tauri commands at https://tauri.app/develop/calling-rust/
    setGreetMsg(await invoke("greet", { name }));
  }

  return (
    <main className="container">
      <h1>Welcome to Video editor </h1>

      <div className="row">
        <a href="https://vite.dev" target="_blank">
          <img src="/vite.svg" className="logo vite" alt="Vite logo" />
        </a>
        <a href="https://tauri.app" target="_blank">
          <img src="/tauri.svg" className="logo tauri" alt="Tauri logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <p>Click on the Tauri, Vite, and React logos to learn more.</p>

      <form
        className="row"
        onSubmit={(e) => {
          e.preventDefault();
          greet();
        }}
      >
        <input
          id="greet-input"
          onChange={(e) => setName(e.currentTarget.value)}
          placeholder="Enter a name..."
          required
        />
        <button type="submit">Greet</button>
      </form>
      <p>{greetMsg}</p>
    </main>
  );
}

export default App;
